### ISSUE TITLE
Clicking button to load widget causes form submission

### ISSUE THREAD

**Issue by pandydavey** [bubbaspaarx/react-cloudinary-upload-widget#4]
When trying to use your widget each time i click the button to load the widget i get a form submission. I think this would be fixed with a e.preventDefault() on the button onClick.

**Comment by pandydavey** [comment]
There's actually a PR with this solution already, so i guess this can be closed when it's done. 

In the mean time i have created this basic fix that works. It's not ideal but we are where we are. 

```
useEffect(() => {
        // This package doesnt set a type for the button
        // this means when we click on the add photo button the
        // form is submitted because modern browsers assume a button
        // is a submit by default. This meant that each time you tried to
        // add an image the form would submit. Drama llama.
        if (document && document.querySelector('#cloudinary_upload_button')) {
            document
                .getElementById('cloudinary_upload_button')
                .setAttribute('type', 'button');
        }
    }, []);
```

**Comment by nooobcoder** [comment]
Agreed, also we should **never manipulate the DOM** like this in frameworks like React, Angular etc (React in this case).
Great solution towards a fix @pandydavey this is much appreciated.
