### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by proffnick** [bubbaspaarx/react-cloudinary-upload-widget#8]
Using signed uploads, I am getting `"Invalid Signature 94e4146e10a***** String to sign '*****'", `Where **** represents the data returned from Cloudinary. As I inspected the data sent to the `"generateSignatureUrl"` for generating the signature, I realized there are differences between them E.G the `generateSignatureUrl` received this:
```
 {
eager: 'w_400,h_300,c_pad|w_260,h_200,c_crop',
source: 'uw',
timestamp: 1639448586,
unique_filename: true,
upload_preset: 'i0ketrzb'
}
```

Meanwhile the Cloudinary server received this:
```"folder=*foldername*&source=uw&timestamp=1639448586&unique_filename=true&upload_preset=*specific-preset*&use_filename=false" ```as the string to sign. 

If I comment out:
```
use_filename={false}
eager={'w_400,h_300,c_pad|w_260,h_200,c_crop'}
```
and then set 
`folder={''}`
everything seems to work fine.

My question is could that be the cause of the failed upload and thus the error "invalid signature"? How do I move pass here?

**Comment by bubbaspaarx** [comment]
Apologies for the long delay in responding here. 
How are you currently signing the object?

**Comment by proffnick** [comment]
I had to disable "Signed Uploads", and revert to the traditional upload. There are disadvantages with that but, for now, I really have no other choice. Do you have an explanation as to the cause of that error? Any help will be greatly appreciated.

**Comment by bubbaspaarx** [comment]
Currently working on this. I believe this may be a bug with cloudinary. I've fixed one aspect of it but cloudinary seems unable to accept the 'eager' variable at all. It's definitely being passed through for signing but it may well be the SDK they provide to generate the signature that is ignoring it. I'll keep digging.

**Comment by bubbaspaarx** [comment]
Finally received information back from Cloudinary support. Please see response below

```
If you want to use eager transformations you would need to include them in the upload preset you are using in your upload widget.

You can refer to step number 2 here:
https://cloudinary.com/documentation/upload_widget#signed_uploads

To include eager transformations in your Upload Preset go to your settings (at the top right) => Click on Upload => Click on “edit” in the desired upload preset => Click on "Upload Manipulations” tab on the left => Click on “Add eager transformation”.
```

It appears then that eager transformations using the cloudinary upload widget need to be set in the preset itself and cannot be sent through the request from the widget. I will amend the package removing this option to avoid further issues
